### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by Tailslide** [ghybs/Leaflet.TileLayer.Fallback#19]
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at Object.writeFileSync (fs.js:1460:5)
    at Object.exports.build (C:\source\principleworx\blazor\Leaflet.TileLayer.Fallback\build\build.js:106:12)

**Comment by ghybs** [comment]
Hi,

Sorry for the late reply.

Indeed, strangely the first time the build is run (and also on first `npm install`), this error is reported, probably because the build script tries to read a file that does not exist yet.

But on next builds, everything works fine.
Therefore you should be good by simply running the build script again.

I do not think I will have the opportunity to debug this myself unfortunately. PR welcome! :-)

**Comment by Tailslide** [comment]
I wound up writing my own from scratch and incorporating it into a fork of leaflet.offline: https://github.com/allartk/leaflet.offline/pull/72
